name: starter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  pedantic: ^1.8.0
  equatable: ^1.1.0
  flutter_bloc: ^3.2.0
  firebase_analytics: ^5.0.11
  get_it: ^4.0.0
  shared_preferences: ^0.5.6+2
  cloud_firestore: ^0.13.4
  flutter_launcher_icons: ^0.7.4
  bloc_test: ^4.0.0
  google_sign_in: ^4.1.4
  firebase_auth: ^0.15.5+2
  email_validator: ^1.0.4
  password_strength: ^0.1.2
  firebase_core: ^0.4.4+2
  flutter_platform_widgets: ^0.32.4
  flushbar: ^1.9.1
  flutter_auth_buttons: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
