name: flutter_auth
version: 1.0.0+1
description: Flutter starter app providing sign up, sign in and sign out functionnalities.
author: Christophe Bonello
homepage: https://github.com/cbonello/
repository: https://github.com/cbonello/flutter_auth
issue_tracker: https://github.com/cbonello/flutter_auth/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.12.0

dependencies:
  device_preview: ^0.4.4
  email_validator: ^1.0.4
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  flutter:
    sdk: flutter
  flutter_auth_buttons: ^0.8.0
  flutter_bloc: ^4.0.0
  flutter_localizations:
    sdk: flutter
  flutter_platform_widgets: ^0.32.5
  freezed_annotation: ^0.7.1
  google_sign_in: ^4.4.4
  intl: ^0.16.0
  password_strength: ^0.1.2
  rxdart: ^0.24.0
  shared_preferences: ^0.5.7

dev_dependencies:
  bloc_test: ^5.0.0
  build_runner: ^1.8.1
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  freezed: ^0.10.7
  intl_translation: ^0.17.9
  lint: ^1.1.1
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
